In [2]:
import numpy as np
import pandas as pd

In [6]:
dtype_dict = {'bathrooms':float, 'waterfront':int, 'sqft_above':int, 'sqft_living15':float, 'grade':int, 'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str, 'long':float, 'sqft_lot15':float, 'sqft_living':float, 'floors':float, 'condition':int, 'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int}

In [120]:
data=pd.read_csv("kc_house_data_small.csv",dtype=dtype_dict)
train_data=pd.read_csv("kc_house_data_small_train.csv",dtype=dtype_dict)
test_data=pd.read_csv("kc_house_data_small_test.csv",dtype=dtype_dict)
valid_data=pd.read_csv("kc_house_data_validation.csv",dtype=dtype_dict)

In [121]:
data.dtypes

id                object
date              object
price            float64
bedrooms         float64
bathrooms        float64
sqft_living      float64
sqft_lot           int32
floors           float64
waterfront         int32
view               int32
condition          int32
grade              int32
sqft_above         int32
sqft_basement      int32
yr_built           int32
yr_renovated       int32
zipcode           object
lat              float64
long             float64
sqft_living15    float64
sqft_lot15       float64
dtype: object

In [122]:
feature_matrix=data[['sqft_living','bedrooms']]
feature_test=test_data[['sqft_living','bedrooms']]
feature_train=train_data[['sqft_living','bedrooms']]

In [123]:
feature_matrix.shape

(8703, 2)

In [124]:
output=data['price']

In [125]:
output=output.reshape(len(output),1)

In [126]:
output.shape

(8703L, 1L)

In [127]:
def normalize_features(features):
    norms = np.linalg.norm(features, axis=0)
    normalized_features=features/norms
    return (normalized_features, norms)

In [128]:
feature_test.head()

sqft_living  bedrooms
0         2950         4
1         1600         4
2         1520         3
3         1090         3
4         2290         4

In [129]:
feature_test=np.array(feature_test)
feature_train=np.array(feature_train)

In [130]:
feature_test[0,:]

array([ 2950.,     4.])

In [131]:
test_data=np.array(test_data)

In [132]:
test_data.shape

(1741L, 21L)

In [133]:
k=test_data.transpose()

In [134]:
k.shape

(21L, 1741L)

In [137]:
p,q=normalize_features(feature_train)

In [138]:
p

array([[ 0.00703685,  0.01163464],
       [ 0.01532602,  0.01163464],
       [ 0.00459184,  0.00775643],
       ..., 
       [ 0.01353699,  0.01163464],
       [ 0.01502785,  0.01551285],
       [ 0.00912405,  0.01163464]])

In [139]:
p[9]

array([ 0.0083488 ,  0.01163464])

In [140]:
n[0]

array([ 0.03088415,  0.02654835])

In [144]:
np.sqrt(np.sum((n[0]-p[9])**2))

0.02702333691767269

In [145]:
dic={}
for i in range(10):
    d=np.sqrt(np.sum((n[0]-p[i])**2))
    dic[i]=d

In [146]:
dic

{0: 0.028126725526359773,
 1: 0.02155166615489202,
 2: 0.032317518537763677,
 3: 0.022141861414146018,
 4: 0.025647447293132661,
 5: 0.028735963746215225,
 6: 0.025164679138581052,
 7: 0.017765837583624031,
 8: 0.022073821227463309,
 9: 0.02702333691767269}

In [147]:
min(dic, key=dic.get)

7

In [152]:
print feature_train[0:3] - feature_test[0]

[[ -1.77000000e+03  -1.00000000e+00]
 [ -3.80000000e+02  -1.00000000e+00]
 [ -2.18000000e+03  -2.00000000e+00]]


In [153]:
for i in xrange(3):
    print feature_train[i]-feature_test[0]

[ -1.77000000e+03  -1.00000000e+00]
[-380.   -1.]
[ -2.18000000e+03  -2.00000000e+00]


In [ ]:
for i in range(len(feature_train)):
    diff[i]=feature_train[i]-feature_test[]
    dic[i]=d