In [4]:
import numpy as np
import pandas as pd

In [5]:
loans=pd.read_csv('lending-club-data.csv')
loans.head()

C:\Users\Shaurya\Anaconda\lib\site-packages\pandas\io\parsers.py:1170: DtypeWarning: Columns (19,47) have mixed types. Specify dtype option on import or set low_memory=False.
  data = self._reader.read(nrows)


id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0  1077501    1296599       5000         5000             4975   36 months   
1  1077430    1314167       2500         2500             2500   60 months   
2  1077175    1313524       2400         2400             2400   36 months   
3  1076863    1277178      10000        10000            10000   36 months   
4  1075269    1311441       5000         5000             5000   36 months   

   int_rate  installment grade sub_grade          ...          sub_grade_num  \
0     10.65       162.87     B        B2          ...                    0.4   
1     15.27        59.83     C        C4          ...                    0.8   
2     15.96        84.33     C        C5          ...                    1.0   
3     13.49       339.31     C        C1          ...                    0.2   
4      7.90       156.46     A        A4          ...                    0.8   

  delinq_2yrs_zero pub_rec_zero  collections_12_mths_zero short_emp  \
0                1            1                         1         0   
1                1            1                         1         1   
2                1            1                         1         0   
3                1            1                         1         0   
4                1            1                         1         0   

  payment_inc_ratio          final_d last_delinq_none last_record_none  \
0           8.14350  20141201T000000                1                1   
1           2.39320  20161201T000000                1                1   
2           8.25955  20141201T000000                1                1   
3           8.27585  20141201T000000                0                1   
4           5.21533  20141201T000000                1                1   

  last_major_derog_none  
0                     1  
1                     1  
2                     1  
3                     1  
4                     1  

[5 rows x 68 columns]

In [6]:
loans['safe_loans'] = loans['bad_loans'].apply(lambda x : +1 if x==0 else -1)

In [7]:
loans=loans.drop('bad_loans',axis=1)

In [8]:
features = ['grade',                     # grade of the loan
            'sub_grade',                 # sub-grade of the loan
            'short_emp',                 # one year or less of employment
            'emp_length_num',            # number of years of employment
            'home_ownership',            # home_ownership status: own, mortgage or rent
            'dti',                       # debt to income ratio
            'purpose',                   # the purpose of the loan
            'term',                      # the term of the loan
            'last_delinq_none',          # has borrower had a delinquincy
            'last_major_derog_none',     # has borrower had 90 day or worse rating
            'revol_util',                # percent of available credit being used
            'total_rec_late_fee',        # total late fees received to day
           ]

target = 'safe_loans'                    # prediction target (y) (+1 means safe, -1 is risky)

# Extract the feature columns and target column
loans = loans[features + [target]]

In [9]:
train=pd.read_json('https://s3.amazonaws.com/static.dato.com/files/coursera/course-3/indices-json/module-5-assignment-1-train-idx.json')
train_idx=[]
for i in train[0]:
    train_idx.append(i)

In [81]:
valid=pd.read_json('https://s3.amazonaws.com/static.dato.com/files/coursera/course-3/indices-json/module-5-assignment-1-validation-idx.json')
validation_idx=[]
for i in valid[0]:
    validation_idx.append(i)

In [82]:
train_data = loans.iloc[train_idx]
validation_data = loans.iloc[validation_idx]

In [84]:
train_data=pd.get_dummies(train_data)
validation_data=pd.get_dummies(validation_data)
#sample_validation_data=pd.get_dummies(sample_validation_data)

In [86]:
target='safe_loans'

In [85]:
validation_safe_loans = validation_data[validation_data[target] == 1]
validation_risky_loans = validation_data[validation_data[target] == -1]

sample_validation_data_risky = validation_risky_loans[0:2]
sample_validation_data_safe = validation_safe_loans[0:2]

sample_validation_data = sample_validation_data_safe.append(sample_validation_data_risky)
sample_validation_data

short_emp  emp_length_num    dti  last_delinq_none  last_major_derog_none  \
19          0              11  11.18                 1                      1   
79          0              10  16.85                 1                      1   
24          0               3  13.97                 0                      1   
41          0              11  16.33                 1                      1   

    revol_util  total_rec_late_fee  safe_loans  grade_A  grade_B  \
19        82.4                   0           1        0        1   
79        96.4                   0           1        0        0   
24        59.5                   0          -1        0        0   
41        62.1                   0          -1        1        0   

         ...         purpose_house  purpose_major_purchase  purpose_medical  \
19       ...                     0                       0                0   
79       ...                     0                       0                0   
24       ...                     0                       0                0   
41       ...                     0                       0                0   

    purpose_moving  purpose_other  purpose_small_business  purpose_vacation  \
19               0              0                       0                 0   
79               0              0                       0                 0   
24               0              1                       0                 0   
41               0              0                       0                 0   

    purpose_wedding  term_ 36 months  term_ 60 months  
19                0                1                0  
79                0                1                0  
24                0                0                1  
41                0                1                0  

[4 rows x 68 columns]

In [87]:
train_data.head()

short_emp  emp_length_num    dti  last_delinq_none  last_major_derog_none  \
1           1               1   1.00                 1                      1   
6           0               5   5.55                 1                      1   
7           1               1  18.08                 1                      1   
10          1               1  10.08                 1                      1   
12          0               4   7.06                 1                      1   

    revol_util  total_rec_late_fee  safe_loans  grade_A  grade_B  \
1          9.4                   0          -1        0        0   
6         32.6                   0          -1        0        0   
7         36.5                   0          -1        0        1   
10        91.7                   0          -1        0        0   
12        55.5                   0          -1        0        1   

         ...         purpose_house  purpose_major_purchase  purpose_medical  \
1        ...                     0                       0                0   
6        ...                     0                       0                0   
7        ...                     0                       0                0   
10       ...                     0                       0                0   
12       ...                     0                       0                0   

    purpose_moving  purpose_other  purpose_small_business  purpose_vacation  \
1                0              0                       0                 0   
6                0              0                       1                 0   
7                0              1                       0                 0   
10               0              0                       0                 0   
12               0              1                       0                 0   

    purpose_wedding  term_ 36 months  term_ 60 months  
1                 0                0                1  
6                 0                0                1  
7                 0                0                1  
10                0                1                0  
12                0                1                0  

[5 rows x 68 columns]

In [88]:
validation_data.head()

short_emp  emp_length_num    dti  last_delinq_none  \
24           0               3  13.97                 0   
41           0              11  16.33                 1   
60           0               5  12.48                 1   
93           0              11  23.18                 1   
132          0               3   7.83                 1   

     last_major_derog_none  revol_util  total_rec_late_fee  safe_loans  \
24                       1        59.5                   0          -1   
41                       1        62.1                   0          -1   
60                       1        73.9                   0          -1   
93                       1        79.7                   0          -1   
132                      1        65.4                   0          -1   

     grade_A  grade_B       ...         purpose_house  purpose_major_purchase  \
24         0        0       ...                     0                       0   
41         1        0       ...                     0                       0   
60         0        0       ...                     0                       0   
93         0        0       ...                     0                       0   
132        0        1       ...                     0                       0   

     purpose_medical  purpose_moving  purpose_other  purpose_small_business  \
24                 0               0              1                       0   
41                 0               0              0                       0   
60                 0               0              0                       1   
93                 0               0              0                       0   
132                0               0              0                       0   

     purpose_vacation  purpose_wedding  term_ 36 months  term_ 60 months  
24                  0                0                0                1  
41                  0                0                1                0  
60                  0                0                0                1  
93                  0                0                0                1  
132                 0                0                1                0  

[5 rows x 68 columns]

In [89]:
sample_validation_data.head()

short_emp  emp_length_num    dti  last_delinq_none  last_major_derog_none  \
19          0              11  11.18                 1                      1   
79          0              10  16.85                 1                      1   
24          0               3  13.97                 0                      1   
41          0              11  16.33                 1                      1   

    revol_util  total_rec_late_fee  safe_loans  grade_A  grade_B  \
19        82.4                   0           1        0        1   
79        96.4                   0           1        0        0   
24        59.5                   0          -1        0        0   
41        62.1                   0          -1        1        0   

         ...         purpose_house  purpose_major_purchase  purpose_medical  \
19       ...                     0                       0                0   
79       ...                     0                       0                0   
24       ...                     0                       0                0   
41       ...                     0                       0                0   

    purpose_moving  purpose_other  purpose_small_business  purpose_vacation  \
19               0              0                       0                 0   
79               0              0                       0                 0   
24               0              1                       0                 0   
41               0              0                       0                 0   

    purpose_wedding  term_ 36 months  term_ 60 months  
19                0                1                0  
79                0                1                0  
24                0                0                1  
41                0                1                0  

[4 rows x 68 columns]

In [90]:
train_feature=train_data.drop('safe_loans',axis=1)
validation_feature=validation_data.drop('safe_loans',axis=1)
sample_validation_feature=sample_validation_data.drop('safe_loans',axis=1)

In [91]:
train_label=train_data['safe_loans']
validation_label=validation_data['safe_loans']
sample_validation_label=sample_validation_data['safe_loans']

In [92]:
train_feature=np.array(train_feature)
validation_feature=np.array(validation_feature)
sample_validation_feature=np.array(sample_validation_feature)
train_label=np.array(train_label)
validation_label=np.array(validation_label)
sample_validation_label=np.array(sample_validation_label)

In [93]:
from sklearn.tree import DecisionTreeClassifier

In [94]:
decision_tree_model=DecisionTreeClassifier(max_depth=6)
decision_tree_model.fit(train_feature,train_label)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=6,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best')

In [95]:
small_model=DecisionTreeClassifier(max_depth=2)
small_model.fit(train_feature,train_label)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best')

In [96]:
big_model=DecisionTreeClassifier(max_depth=10)
big_model.fit(train_feature,train_label)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best')

In [97]:
decision_train_predict=decision_tree_model.predict(train_feature)
decision_validation_predict=decision_tree_model.predict(validation_feature)
small_train_predict=small_model.predict(train_feature)
small_validation_predict=small_model.predict(validation_feature)
big_train_predict=big_model.predict(train_feature)
big_validation_predict=big_model.predict(validation_feature)

In [98]:
decision_tree_model.predict(sample_validation_feature)

array([ 1, -1, -1,  1], dtype=int64)

In [99]:
decision_tree_model.predict_proba(sample_validation_feature)

array([[ 0.34156543,  0.65843457],
       [ 0.53630646,  0.46369354],
       [ 0.64750958,  0.35249042],
       [ 0.20789474,  0.79210526]])

In [100]:
small_model.predict(sample_validation_feature)

array([ 1, -1, -1,  1], dtype=int64)

In [101]:
small_model.predict_proba(sample_validation_feature)

array([[ 0.41896585,  0.58103415],
       [ 0.59255339,  0.40744661],
       [ 0.59255339,  0.40744661],
       [ 0.23120112,  0.76879888]])

In [102]:
from sklearn.metrics import accuracy_score

In [103]:
accuracy_score(train_label,decision_train_predict)

0.64052761659144641

In [104]:
accuracy_score(train_label,small_train_predict)

0.61350204169353106

In [105]:
accuracy_score(train_label,big_train_predict)

0.66379217709004945

In [108]:
accuracy_score(validation_label,decision_validation_predict)

0.63614821197759586

In [109]:
accuracy_score(validation_label,small_validation_predict)

0.61934510986643687

In [110]:
accuracy_score(validation_label,big_validation_predict)

0.62645411460577338

In [112]:

false_positives = 0

for i in range(len(validation_data)):
    if validation_label[i] == -1 and decision_validation_predict[i] == +1:
        false_positives += 1

print false_positives

1661


In [114]:
false_negatives = 0

for i in range(len(validation_data)):
    if validation_label[i] == +1 and decision_validation_predict[i]== -1:
        false_negatives += 1

print false_negatives

1717


In [115]:
print false_negatives*10000 + false_positives*20000

50390000
