In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from math import sqrt

In [45]:
data=pd.read_csv("kc_house_data.csv")
train_data=pd.read_csv("kc_house_train_data.csv")
test_data=pd.read_csv("kc_house_test_data.csv")

In [46]:
data.head()

id             date   price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900         3       1.00         1180   
1  6414100192  20141209T000000  538000         3       2.25         2570   
2  5631500400  20150225T000000  180000         2       1.00          770   
3  2487200875  20141209T000000  604000         4       3.00         1960   
4  1954400510  20150218T000000  510000         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650       1           0     0     ...          7        1180   
1      7242       2           0     0     ...          7        2170   
2     10000       1           0     0     ...          6         770   
3      5000       1           0     0     ...          7        1050   
4      8080       1           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [47]:
feature_sqft=np.array([np.ones(17384),train_data['sqft_living']])
feature_sqft=feature_sqft.transpose()

In [48]:
multiple_feature=np.array([np.ones(17384),train_data['sqft_living'],train_data['sqft_living15']])
multiple_feature=multiple_feature.transpose()

In [49]:
multiple_feature

array([[  1.00000000e+00,   1.18000000e+03,   1.34000000e+03],
       [  1.00000000e+00,   2.57000000e+03,   1.69000000e+03],
       [  1.00000000e+00,   7.70000000e+02,   2.72000000e+03],
       ..., 
       [  1.00000000e+00,   1.53000000e+03,   1.53000000e+03],
       [  1.00000000e+00,   1.60000000e+03,   1.41000000e+03],
       [  1.00000000e+00,   1.02000000e+03,   1.02000000e+03]])

In [50]:
feature_sqft_test=np.array([np.ones(len(test_data)),test_data['sqft_living']])
feature_sqft_test=feature_sqft_test.transpose()

In [51]:
multiple_feature_test=np.array([np.ones(len(test_data)),test_data['sqft_living'],test_data['sqft_living15']])
multiple_feature_test=multiple_feature_test.transpose()

In [52]:
feature_sqft_test.shape

(4229L, 2L)

In [53]:
feature=np.array([np.ones(17384),data])

In [54]:
feature_sqft

array([[  1.00000000e+00,   1.18000000e+03],
       [  1.00000000e+00,   2.57000000e+03],
       [  1.00000000e+00,   7.70000000e+02],
       ..., 
       [  1.00000000e+00,   1.53000000e+03],
       [  1.00000000e+00,   1.60000000e+03],
       [  1.00000000e+00,   1.02000000e+03]])

In [55]:
def predict_output(feature_matrix, weights):
    output=np.dot(feature_matrix,weights)
    return(output)

In [56]:
def feature_derivative(errors, feature,weights,l2_penalty):
    derivative = 2*np.dot(errors, feature) + 2*l2_penalty*weights
    return(derivative)

In [57]:
def regression_gradient_descent(feature_matrix,output,initial_weights,step_size,l2_penalty,max_iterations=100):
    weights = initial_weights
    prediction=predict_output(feature_matrix,weights)
    gradient_magnitude=0
    iteration=0
    converged=False
    while not converged:
        prediction=predict_output(feature_matrix,weights)
        error=prediction-output
        gradient_sum_square=0
        for i in range(len(weights)):
            if i==0:
                derivative=2*np.dot(error, feature_matrix[:,i])
            else:    
                derivative=feature_derivative(error, feature_matrix[:,i],weights[i],l2_penalty)
            gradient_sum_square+= derivative*derivative
            weights[i]-=(step_size*derivative)
        gradient_magnitude=sqrt(gradient_sum_square)
        iteration+=1
        print weights
        print gradient_magnitude
        if (iteration > max_iterations):
            converged=True
    return(weights)
       

In [77]:
simple_weights_0_penalty=regression_gradient_descent(feature_sqft,train_data['price'],np.array([0.0,0.0]),1e-12,0.0,max_iterations=1000)

[  1.87526989e-02   4.73325137e+01]
4.73325174213e+13
[  3.40823824e-02   8.61473080e+01]
3.88147973584e+13
[  4.66050390e-02   1.17977189e+02]
3.18298830499e+13
[  5.68258070e-02   1.44079125e+02]
2.61019385371e+13
[  6.51589226e-02   1.65483889e+02]
2.14047659029e+13
[  7.19440782e-02   1.83036761e+02]
1.75528726616e+13
[  7.74598369e-02   1.97430906e+02]
1.43941466157e+13
[  8.19346328e-02   2.09234754e+02]
1.1803848908e+13
[  8.55557924e-02   2.18914442e+02]
9.67968805441e+12
[  8.84769317e-02   2.26852222e+02]
7.93778042794e+12
[  9.08240229e-02   2.33361559e+02]
6.5093376743e+12
[  9.27003687e-02   2.38699509e+02]
5.33795024294e+12
[  9.41906821e-02   2.43076868e+02]
4.37735976033e+12
[  9.53644315e-02   2.46666500e+02]
3.58963227551e+12
[  9.62785842e-02   2.49610161e+02]
2.9436602392e+12
[  9.69798558e-02   2.52024094e+02]
2.41393405913e+12
[  9.75065555e-02   2.54003629e+02]
1.97953472007e+12
[  9.78900982e-02   2.55626937e+02]
1.62330768685e+12
[  9.81562458e-02   2.56958122e

In [78]:
simple_weights_0_penalty

array([ -1.63382329e-01,   2.63024369e+02])

In [118]:
simple_weights_penalty=regression_gradient_descent(feature_sqft,train_data['price'],simple_weights_0_penalty,1e-12,1e11,max_iterations=1000)

[   9.5733504   124.57221259]
9743495134.14
[   9.5830939   124.57221074]
9743494929.5
[   9.59283739  124.57220888]
9743494724.85
[   9.60258089  124.57220703]
9743494520.21
[   9.61232438  124.57220517]
9743494315.56
[   9.62206787  124.57220332]
9743494110.92
[   9.63181137  124.57220146]
9743493906.27
[   9.64155486  124.57219961]
9743493701.62
[   9.65129835  124.57219775]
9743493496.98
[   9.66104185  124.5721959 ]
9743493292.33
[   9.67078534  124.57219404]
9743493087.69
[   9.68052883  124.57219219]
9743492883.04
[   9.69027233  124.57219034]
9743492678.4
[   9.70001582  124.57218848]
9743492473.75
[   9.70975931  124.57218663]
9743492269.1
[   9.7195028   124.57218477]
9743492064.46
[   9.72924629  124.57218292]
9743491859.81
[   9.73898978  124.57218106]
9743491655.17
[   9.74873328  124.57217921]
9743491450.52
[   9.75847677  124.57217735]
9743491245.88
[   9.76822026  124.5721755 ]
9743491041.23
[   9.77796375  124.57217365]
9743490836.59
[   9.78770724  124.57217179]
97434

In [119]:
simple_weights_penalty

array([  19.31674293,  124.57035809])

In [120]:
k=predict_output(feature_sqft_test,simple_weights_penalty)
np.sum((k-test_data['price'])**2)

694630135137793.2

In [111]:
multiple_weights_0_penalty=regression_gradient_descent(multiple_feature,train_data['price'],np.array([0.0,0.0,0.0]),1e-12,0.0,max_iterations=1000)

[  1.87526989e-02   4.73325137e+01   4.23911280e+01]
6.35403410474e+13
[  3.11553143e-02   7.93537161e+01   7.06890272e+01]
4.27332265788e+13
[  3.92882612e-02   1.01077531e+02   8.95110259e+01]
2.87435525845e+13
[  4.45505334e-02   1.15875629e+02   1.01962087e+02]
1.93394064906e+13
[  4.78828954e-02   1.26015332e+02   1.10130166e+02]
1.30204115961e+13
[  4.99179711e-02   1.33021331e+02   1.15419326e+02]
8.77833904071e+12
[  5.10811722e-02   1.37918927e+02   1.18773733e+02]
5.9362018913e+12
[  5.16585678e-02   1.41397600e+02   1.20828296e+02]
4.04009840619e+12
[  5.18425255e-02   1.43921004e+02   1.22009959e+02]
2.78637734735e+12
[  5.17624017e-02   1.45800937e+02   1.22605817e+02]
1.97210384437e+12
[  5.15051806e-02   1.47247074e+02   1.22808924e+02]
1.46033072876e+12
[  5.11293527e-02   1.48400422e+02   1.22749093e+02]
1.15489900691e+12
[  5.06742477e-02   1.49355808e+02   1.22513611e+02]
9.8397868463e+11
[  5.01663105e-02   1.50177006e+02   1.22161170e+02]
8.9363345578e+11
[  4.9623

In [112]:
multiple_weights_0_penalty

array([  -0.35780714,  243.05572642,   22.41312485])

In [114]:
multiple_weights_penalty=regression_gradient_descent(multiple_feature,train_data['price'],multiple_weights_0_penalty,1e-12,1e11,max_iterations=1000)

[  -0.35817946  194.44612851   17.92881979]
4.88160014905e+13
[  -0.35472676  165.02463944   22.81995227]
2.98252780007e+13
[  -0.34948407  145.9981375    30.69707008]
2.05926391846e+13
[  -0.34340933  132.93846292   38.83868039]
1.53896379312e+13
[  -0.3369523   123.5361028    46.19503842]
1.19381916913e+13
[  -0.33032325  116.5272869    52.45762331]
9.3991230293e+12
[  -0.32361977  111.17786416   57.62951288]
7.44075334842e+12
[  -0.31688653  107.03213456   61.83035179]
5.90204767372e+12
[  -0.31014355  103.78836934   65.21051872]
4.68482515569e+12
[  -0.30339938  101.2353834    67.91558602]
3.71956607561e+12
[ -0.29665737  99.21890307  70.07350831]
2.95345001577e+12
[ -0.28991853  97.62276574  71.79173002]
2.34520482336e+12
[ -0.2831829   96.35772633  73.15832843]
1.8622462997e+12
[ -0.27645015  95.35433363  74.24454643]
1.4787534585e+12
[ -0.26971984  94.55810738  75.10757165]
1.17423764493e+12
[ -0.26299154  93.92610251  75.79310592]
9.32433735486e+11
[ -0.25626486  93.42436694  7

In [115]:
multiple_weights_penalty

array([  6.35642235,  91.48932524,  78.43663977])

In [113]:
k=predict_output(multiple_feature_test,multiple_weights_0_penalty)
print np.sum((k-test_data['price'])**2)
print k[0]

2.74067691979e+14
387464.693213


In [116]:
k=predict_output(multiple_feature_test,multiple_weights_penalty)
print np.sum((k-test_data['price'])**2)
print k[0]

5.00405014564e+14
270453.310314
