In [118]:
import numpy as np
import pandas as pd

In [119]:
data=pd.read_csv("kc_house_data.csv")
train_data=pd.read_csv("kc_house_train_data.csv")
test_data=pd.read_csv("kc_house_test_data.csv")

In [120]:
train_data.head()

id             date   price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900         3       1.00         1180   
1  6414100192  20141209T000000  538000         3       2.25         2570   
2  5631500400  20150225T000000  180000         2       1.00          770   
3  2487200875  20141209T000000  604000         4       3.00         1960   
4  1954400510  20150218T000000  510000         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650       1           0     0     ...          7        1180   
1      7242       2           0     0     ...          7        2170   
2     10000       1           0     0     ...          6         770   
3      5000       1           0     0     ...          7        1050   
4      8080       1           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [121]:
train_data['bedroom_squared']=train_data['bedrooms']**2
train_data['bed_bath']=train_data['bedrooms']*train_data['bathrooms']
train_data['log_sqft']=np.log(train_data['sqft_living'])
train_data['lat_long']=train_data['lat']+train_data['long']

In [122]:
train_data.head()

id             date   price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900         3       1.00         1180   
1  6414100192  20141209T000000  538000         3       2.25         2570   
2  5631500400  20150225T000000  180000         2       1.00          770   
3  2487200875  20141209T000000  604000         4       3.00         1960   
4  1954400510  20150218T000000  510000         3       2.00         1680   

   sqft_lot  floors  waterfront  view    ...     yr_renovated  zipcode  \
0      5650       1           0     0    ...                0    98178   
1      7242       2           0     0    ...             1991    98125   
2     10000       1           0     0    ...                0    98028   
3      5000       1           0     0    ...                0    98136   
4      8080       1           0     0    ...                0    98074   

       lat     long  sqft_living15  sqft_lot15  bedroom_squared  bed_bath  \
0  47.5112 -122.257           1340        5650                9      3.00   
1  47.7210 -122.319           1690        7639                9      6.75   
2  47.7379 -122.233           2720        8062                4      2.00   
3  47.5208 -122.393           1360        5000               16     12.00   
4  47.6168 -122.045           1800        7503                9      6.00   

   log_sqft  lat_long  
0  7.073270  -74.7458  
1  7.851661  -74.5980  
2  6.646391  -74.4951  
3  7.580700  -74.8722  
4  7.426549  -74.4282  

[5 rows x 25 columns]

In [123]:
test_data['bedroom_squared']=test_data['bedrooms']**2
test_data['bed_bath']=test_data['bedrooms']*test_data['bathrooms']
test_data['log_sqft']=np.log(test_data['sqft_living'])
test_data['lat_long']=test_data['lat']+test_data['long']

In [169]:
test_data['bedroom_squared'].mean()

12.446677701584299

In [170]:
test_data['bed_bath'].mean()

7.5039016315913925

In [171]:
test_data['log_sqft'].mean()

7.5502746796459208

In [172]:
test_data['lat_long'].mean()

-74.653333554031846

## Train data

In [124]:
train_data.shape

(17384, 25)

In [125]:
model_1_H=np.array([train_data['sqft_living'],train_data['bedrooms'],train_data['bathrooms'],train_data['lat'],train_data['long']])

In [126]:
model_1_H.shape

(5L, 17384L)

In [127]:
model_1_H=model_1_H.transpose()

In [128]:
model_1_H.shape

(17384L, 5L)

In [129]:
model_1_H

array([[  1.18000000e+03,   3.00000000e+00,   1.00000000e+00,
          4.75112000e+01,  -1.22257000e+02],
       [  2.57000000e+03,   3.00000000e+00,   2.25000000e+00,
          4.77210000e+01,  -1.22319000e+02],
       [  7.70000000e+02,   2.00000000e+00,   1.00000000e+00,
          4.77379000e+01,  -1.22233000e+02],
       ..., 
       [  1.53000000e+03,   3.00000000e+00,   2.50000000e+00,
          4.76993000e+01,  -1.22346000e+02],
       [  1.60000000e+03,   3.00000000e+00,   2.50000000e+00,
          4.75345000e+01,  -1.22069000e+02],
       [  1.02000000e+03,   2.00000000e+00,   7.50000000e-01,
          4.75941000e+01,  -1.22299000e+02]])

In [130]:
model_2_H=np.array([train_data['sqft_living'],train_data['bedrooms'],train_data['bathrooms'],train_data['lat'],train_data['long'],train_data['bed_bath']])

In [131]:
model_2_H=model_2_H.transpose()

In [132]:
model_3_H=np.array([train_data['sqft_living'],train_data['bedrooms'],train_data['bathrooms'],train_data['lat'],train_data['long'],train_data['bed_bath'],train_data['log_sqft'],train_data['lat_long']])

In [133]:
model_3_H=model_3_H.transpose()

In [134]:
model_2_H.shape

(17384L, 6L)

In [135]:
model_3_H.shape

(17384L, 8L)

In [136]:
output=np.reshape(train_data['price'],(17384,1))

## Test data

In [137]:
model_1_H_test=np.array([test_data['sqft_living'],test_data['bedrooms'],test_data['bathrooms'],test_data['lat'],test_data['long']])
model_2_H_test=np.array([test_data['sqft_living'],test_data['bedrooms'],test_data['bathrooms'],test_data['lat'],test_data['long'],test_data['bed_bath']])
model_3_H_test=np.array([test_data['sqft_living'],test_data['bedrooms'],test_data['bathrooms'],test_data['lat'],test_data['long'],test_data['bed_bath'],test_data['log_sqft'],test_data['lat_long']])

In [138]:
model_1_H_test=model_1_H_test.transpose()
model_2_H_test=model_2_H_test.transpose()
model_3_H_test=model_3_H_test.transpose()

In [152]:
model_1_H_test.shape

(4229L, 5L)

In [140]:
output_test=np.reshape(test_data['price'],(4229,1))

## Linear regression

In [141]:
def multiple_regression(input_feature,output):
    from sklearn.linear_model import LinearRegression
    linreg=LinearRegression()
    linreg.fit(input_feature,output)
    return(linreg)

In [159]:
linreg_1=multiple_regression(model_1_H,output)
linreg_2=multiple_regression(model_2_H,output)
linreg_3=multiple_regression(model_3_H,output)
linreg_1_test=multiple_regression(model_1_H_test,output_test)
linreg_2_test=multiple_regression(model_2_H_test,output_test)
linreg_3_test=multiple_regression(model_3_H_test,output_test)

In [143]:
linreg_1.coef_

array([[  3.12258646e+02,  -5.95865332e+04,   1.57067421e+04,
          6.58619264e+05,  -3.09374351e+05]])

In [144]:
linreg_2.coef_

array([[  3.06610053e+02,  -1.13446368e+05,  -7.14613083e+04,
          6.54844630e+05,  -2.94298969e+05,   2.55796520e+04]])

In [145]:
linreg_3.coef_

array([[  5.32283570e+02,   1.19729718e+03,   9.43375254e+04,
          1.43101722e+13,   1.43101712e+13,  -1.62724575e+04,
         -5.64709006e+05,  -1.43101715e+13]])

In [146]:
linreg_1.intercept_

array([-69075726.79257046])

In [147]:
linreg_2.intercept_

array([-66867968.87107954])

In [148]:
linreg_3.intercept_

array([-61463916.12206627])

In [149]:
from sklearn import metrics

In [174]:
rss_1=(metrics.mean_squared_error(output,linreg_1.predict(model_1_H)))*model_1_H.shape[0]
rss_2=(metrics.mean_squared_error(output,linreg_2.predict(model_2_H)))*model_2_H.shape[0]
rss_3=(metrics.mean_squared_error(output,linreg_3.predict(model_3_H)))*model_3_H.shape[0]
rss_1_test=(metrics.mean_squared_error(output_test,linreg_1_test.predict(model_1_H_test)))*model_1_H_test.shape[0]
rss_2_test=(metrics.mean_squared_error(output_test,linreg_2_test.predict(model_2_H_test)))*model_2_H_test.shape[0]
rss_3_test=(metrics.mean_squared_error(output_test,linreg_3_test.predict(model_3_H_test)))*model_3_H_test.shape[0]

In [175]:
print rss_1,rss_2,rss_3

9.6787996305e+14 9.58419635074e+14 9.04510865701e+14


In [176]:
print rss_1_test,rss_2_test,rss_3_test

2.23588470558e+14 2.20888287428e+14 2.12036177354e+14
