In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv("kc_house_data.csv")
train_data=pd.read_csv("kc_house_train_data.csv")
test_data=pd.read_csv("kc_house_test_data.csv")

In [4]:
def simple_linear_regression(input_feature, output):
    from sklearn.linear_model import LinearRegression
    linreg=LinearRegression()
    linreg.fit(input_feature,output)
    intercept=linreg.intercept_
    slope=linreg.coef_
    return(intercept,slope,linreg)

In [5]:
train_data.head()

id             date   price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900         3       1.00         1180   
1  6414100192  20141209T000000  538000         3       2.25         2570   
2  5631500400  20150225T000000  180000         2       1.00          770   
3  2487200875  20141209T000000  604000         4       3.00         1960   
4  1954400510  20150218T000000  510000         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650       1           0     0     ...          7        1180   
1      7242       2           0     0     ...          7        2170   
2     10000       1           0     0     ...          6         770   
3      5000       1           0     0     ...          7        1050   
4      8080       1           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [6]:
input_feature=train_data['sqft_living']
output=train_data['price']

In [7]:
input_feature.shape

(17384L,)

In [98]:
input_feature=np.reshape(input_feature,(17384,1))
output=np.reshape(output,(17384,1))

In [99]:
type(output[0])

numpy.ndarray

In [100]:
sqft_intercept,sqft_slope,linreg=simple_linear_regression(input_feature, output)

In [101]:
print sqft_intercept
print sqft_slope

[-47116.07907289]
[[ 281.95883963]]


In [102]:
def get_regression_predictions(input_feature, intercept, slope):
    predicted_output=intercept+(slope*input_feature)
    return(predicted_output)

In [103]:
price=get_regression_predictions(2650, sqft_intercept, sqft_slope)

In [104]:
print price

[[ 700074.84594751]]


In [105]:
print linreg.predict(2650)

[[ 700074.84594751]]


In [106]:
def get_residual_sum_of_squares(input_feature, output, intercept,slope):
    RSS=(output-(intercept+(slope*input_feature)))**2
    RSS=RSS.sum()
    return(RSS) 

In [125]:
input_feature

array([[1180],
       [2570],
       [ 770],
       ..., 
       [1530],
       [1600],
       [1020]], dtype=int64)

In [126]:
 output

array([[ 221900.],
       [ 538000.],
       [ 180000.],
       ..., 
       [ 360000.],
       [ 400000.],
       [ 325000.]])

In [127]:
sqft_slope*input_feature

array([[ 332711.4307638 ],
       [ 724634.21784997],
       [ 217108.30651536],
       ..., 
       [ 431397.02463442],
       [ 451134.14340854],
       [ 287598.01642295]])

In [107]:
rss_train_data=get_residual_sum_of_squares(input_feature, output, sqft_intercept, sqft_slope)

In [108]:
print rss_train_data 

1.20191835418e+15


In [109]:
linreg.score(input_feature,output)

0.49409140136495266

In [110]:
def inverse_regression_predictions(output, intercept, slope):
    estimated_input=(output-intercept)/slope
    return(estimated_input)

In [111]:
est_input=inverse_regression_predictions(800000, sqft_intercept, sqft_slope)

In [112]:
print est_input

[[ 3004.39624515]]


In [115]:
input_feature_bedroom=train_data['bedrooms']
input_feature_bedroom=np.reshape(input_feature_bedroom,(17384,1))

In [116]:
output.shape

(17384L, 1L)

In [117]:
bedroom_intercept,bedroom_slope,linreg_1=simple_linear_regression(input_feature_bedroom,output)

In [118]:
test_sqft=test_data['sqft_living']
test_bedroom=test_data['bedrooms']
test_output=test_data['price']

In [119]:
test_sqft.shape

(4229L,)

In [120]:
test_sqft=np.reshape(test_sqft,(4229,1))
test_bedroom=np.reshape(test_bedroom,(4229,1))
test_output=np.reshape(test_output,(4229,1))

In [121]:
rss_test_sqft=get_residual_sum_of_squares(test_sqft, test_output, sqft_intercept,sqft_slope)

In [122]:
rss_test_bedroom=get_residual_sum_of_squares(test_bedroom, test_output, bedroom_intercept,bedroom_slope)

In [123]:
print rss_test_sqft

2.75402933618e+14


In [124]:
print rss_test_bedroom

4.9336458596e+14


In [74]:
linreg.score(input_feature,output)

0.48768545418983145