In [3]:
import numpy as np
import pandas as pd

In [4]:
data=pd.read_csv("kc_house_data.csv")
train_data=pd.read_csv("kc_house_train_data.csv")
test_data=pd.read_csv("kc_house_test_data.csv")

In [5]:
a=np.array([[1,2,3],[4,5,6]])

In [6]:
b=np.ones(3)

In [7]:
b

array([ 1.,  1.,  1.])

In [8]:
a=np.array([b,a[0],a[1]])

In [9]:
a

array([[ 1.,  1.,  1.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [10]:
c=np.array([7,8,9])

In [11]:
a=a.transpose()
c=c.transpose()

In [12]:
o=np.array([5,4,9])
o=o.transpose()

In [13]:
o.shape

(3L,)

In [14]:
def predict_outcome(feature_matrix,weights):
    predictions=feature_matrix.transpose()*weights
    predictions=predictions.sum(1)
    return(predictions)

In [15]:
p=(a.transpose()*c).sum(1)

In [16]:
print p

[  24.   50.  122.]


In [17]:
p.shape

(3L,)

In [18]:
def error_in_outcome(output,prediction):
    errors=output-prection
    return(errors)

In [19]:
e=o-p

In [20]:
e

array([ -19.,  -46., -113.])

In [21]:
(2*e)*a

array([[  -38.,   -92.,  -904.],
       [  -38.,  -184., -1130.],
       [  -38.,  -276., -1356.]])

In [22]:
e.shape

(3L,)

In [33]:
def regression_gradient_descent(feature_matrix,output,initial_weights,step_size,tolerance):
    converged=False
    weights=initial_weights
    tmp=zeros(weights.shape)
    while (converged==False):
        prediction=predict_outcome(feature_matrix,weights)
        error=error_in_outcome(output,prediction)
        gradient_descent=feature_derivative(error,feature_matrix)
        if (sqrt(((gradient_descent)**2).sum())>tolerance):
            for i in range(feature_matrix.shape[1]):
                tmp[i]=gradient_descent*feature_matrix[:,1]
                tmp[i]=weights[i]-(step_size*tmp[i].)
            weights=tmp
        else:
            converged==True
        return(weights)
        
        

In [25]:
a

array([[ 1.,  1.,  4.],
       [ 1.,  2.,  5.],
       [ 1.,  3.,  6.]])

In [30]:
a[0]

array([ 1.,  1.,  4.])